DROP TABLE address IF EXISTS;
DROP TABLE company IF EXISTS;

CREATE TABLE IF NOT EXISTS company (
	id INTEGER PRIMARY KEY, 
	name VARCHAR(256) NOT NULL, 
	description VARCHAR(256) NOT NULL, 
	year INTEGER NOT NULL
	);
	
	CREATE SEQUENCE company_seq AS INTEGER START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS address (
	id INTEGER PRIMARY KEY, 
	company_id INTEGER NOT NULL,
	street VARCHAR(256) NOT NULL, 
	building INTEGER NOT NULL, 
	city VARCHAR(256) NOT NULL,
	country VARCHAR(256) NOT NULL
	);
	
	CREATE SEQUENCE address_seq AS INTEGER START WITH 1 INCREMENT BY 1;
	
	ALTER TABLE address
    ADD FOREIGN KEY (company_id) 
    REFERENCES company (id) 
    ON DELETE CASCADE;